language: generic
os: linux
dist: bionic

branches:
  only:
  - master

cache: 
  pip: true
  yarn: true

stages:
  - name: update data
  - name: build web

jobs:
  include:
    - stage: update data
      language: python
      python: 3.7
      install: pip install -r requirements.txt
      script: 
        - python update.py
        - sh ci-push.sh
    - stage: build web
      language: node_js
      node_js: node
      install: yarn --frozen-lockfile
      script: yarn build
      deploy:
        provider: pages
        local_dir: dist
        cleanup: false
        github_token: $GITHUB_TOKEN
        keep_history: true
