language: generic
os: linux
dist: bionic

branches:
  only:
  - master

cache: 
  pip: true
  yarn: true

stages:
  - name: fetch-data
  - name: build-web
  - name: deploy-web

jobs:
  include:
    - stage: fetch-data
      language: python
      python: 
        -"3.7"
      install: pip install -r requirements.txt
      script: 
        - python update.py
        - sh ci-push.sh
    - stage: build-web
      language: node_js
      install: yarn --frozen-lockfile
      script: yarn build
    - stage: deploy-web
      deploy:
        provider: pages
        local_dir: ./dist/
        cleanup: false
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: master
    